title: "Devis Decet"
author: "Devis Decet"
description: "Personal academic website"
baseurl: ""
url: "https://devisdecet.com" # your GitHub Pages URL

markdown: kramdown
theme: null # we use custom CSS
plugins: []

# Optional: exclude these files from build
exclude:
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock
