relativeURLs = true
title = "Devis Decet"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Ph.D. Candidate in Economics, Northwestern University"
    logo = "headshot/dev_pic.jpg" 
    
